"""Headless satellite image download contracts and request validation."""

from thucthengay.download.filename import (
    compile_filename_format,
    filename_format_warnings,
    filter_matches_by_filename_metadata,
    parse_filename_metadata,
    sample_filename_from_format,
    should_skip_for_cloud,
)
from thucthengay.download.matching import match_source_images
from thucthengay.download.models import (
    DownloadFilenameFilterResult,
    DownloadFilenameFormatRule,
    DownloadFilenameMetadata,
    DownloadGeoJsonArea,
    DownloadImageFolder,
    DownloadImageMatch,
    DownloadManifestRow,
    DownloadMatchResult,
    DownloadOutputResult,
    DownloadRasterCandidate,
    DownloadRasterMetadata,
    DownloadRunStatus,
    DownloadStats,
    FailedDownloadImage,
    PreparedDownloadImage,
    ResolvedSatelliteDownloadRequest,
    SatelliteDownloadProgress,
    SatelliteDownloadRequest,
    SatelliteDownloadResult,
    SkippedCloudDownloadCandidate,
    SkippedCloudDownloadImage,
    SkippedExistingDownloadImage,
)
from thucthengay.download.output import destination_for, write_download_outputs
from thucthengay.download.service import SatelliteDownloadConfigError, resolve_download_request

__all__ = [
    "DownloadFilenameFilterResult",
    "DownloadFilenameFormatRule",
    "DownloadFilenameMetadata",
    "DownloadGeoJsonArea",
    "DownloadImageFolder",
    "DownloadImageMatch",
    "DownloadManifestRow",
    "DownloadMatchResult",
    "DownloadOutputResult",
    "DownloadRasterCandidate",
    "DownloadRasterMetadata",
    "DownloadRunStatus",
    "DownloadStats",
    "FailedDownloadImage",
    "PreparedDownloadImage",
    "ResolvedSatelliteDownloadRequest",
    "SatelliteDownloadConfigError",
    "SatelliteDownloadProgress",
    "SatelliteDownloadRequest",
    "SatelliteDownloadResult",
    "SkippedCloudDownloadCandidate",
    "SkippedCloudDownloadImage",
    "SkippedExistingDownloadImage",
    "compile_filename_format",
    "destination_for",
    "filename_format_warnings",
    "filter_matches_by_filename_metadata",
    "match_source_images",
    "parse_filename_metadata",
    "resolve_download_request",
    "sample_filename_from_format",
    "should_skip_for_cloud",
    "write_download_outputs",
]
